CREATE TABLE Board (
   BDNO NUMBER(8) PRIMARY KEY,
   BDCG NUMBER(10),
   BDTITLE VARCHAR2(150),
   MEMNO NUMBER(8) REFERENCES Member(memno),
   BDCONTENT CLOB,
   BDGROUP NUMBER(10) NOT NULL,
   BDDEPTH NUMBER(10) NOT NULL,
   BDVIEW NUMBER(10),
   BDHIT NUMBER(10),
   BDCDATE DATE,
   BDUDATE DATE
);
