--  테이블삭제
  DROP TABLE REPLY;
  DROP SEQUENCE REPLY_RPNO_SEQ;


-- 댓글번호 시퀀스  
  CREATE SEQUENCE REPLY_RPNO_SEQ START WITH 1
  INCREMENT BY 1;
  
 
-- 댓글테이블
  CREATE TABLE REPLY (
	RPNO        NUMBER(8),
	BDNO 		NUMBER(8),
	MEMNO       NUMBER(8),
	RPCOMMENT 	CLOB,
	RPCDATE     timestamp default systimestamp,
	RPUDATE     timestamp default systimestamp
  );
  
 ALTER TABLE REPLY ADD CONSTRAINT REPLY_RPNO_PK PRIMARY KEY (RPNO);
 ALTER TABLE REPLY ADD CONSTRAINT REPLY_BDNO_FK FOREIGN KEY (BDNO)
      REFERENCES BOARD(BDNO);
 ALTER TABLE REPLY ADD CONSTRAINT REPLY_MEMNO_FK FOREIGN KEY (MEMNO)
      REFERENCES MEMBER(MEMNO);          
 ALTER TABLE REPLY MODIFY BDNO CONSTRAINT REPLY_BDNO_NN NOT NULL;      
 ALTER TABLE REPLY MODIFY MEMNO CONSTRAINT REPLY_MEMNO_NN NOT NULL;      
 ALTER TABLE REPLY MODIFY RPCOMMENT CONSTRAINT REPLY_RPCOMMENT_NN NOT NULL;      
 ALTER TABLE REPLY MODIFY RPCDATE CONSTRAINT BOARD_RPCDATE_NN NOT NULL;
 ALTER TABLE REPLY MODIFY RPUDATE CONSTRAINT BOARD_RPUDATE_NN NOT NULL;    
  
  
 
--게시판 추가 test
 INSERT INTO BOARD (BDNO, BDCG,BDTITLE,MEMNO,BDCONTENT)
 VALUES (BOARD_BDNO_SEQ.nextval, '자유게시판' ,'제목',1,'댓글내용입니다.');
 

--댓글 추가 test
 INSERT INTO REPLY(RPNO, BDNO,MEMNO,RPCOMMENT)
 VALUES (REPLY_RPNO_SEQ.nextval, BOARD_BDNO_SEQ.currval, 1,'댓글내용');
 
 SELECT * FROM REPLY;
  

